# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '动画' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 动画


  pod 'Masonry', '1.0.1'


end
